---
title: "MigraiNe Analysis"
output: html_notebook
---

```{r setup}

library(coda)

```

# Function to convert g to sigma^2

```{r}

g_to_sigma2 <- function(g, twoD = F){
# This converts estimates of g to estimates of sigma^2 according to equations 1 & 2 in
# Rousset and Leblois 2012. twoD is a boolean (T/F) for whether to convert g for
# a 1 or 2 dimensional IBD model (default is 1 dimension).
# This was originally an internal function from Rousset and Leblois (2007) blackbox R package.
  if(twoD) {
    return((1 + g)/((2 - g) * (1 - g)^2))
  }
  else return((1 + g)/((1 - g)^2))
}
```


```{r}
pointls <- read_delim("./migraine/run10/pointls_1.txt", delim = " ", comment = "#", col_names=F)
pointls <- pointls[,c(1:4)]
names(pointls) <- c("twoNeu","twoNem","g","LogL")
lattice2geog <- 49.35
pointls$conds2 <- g_to_sigma2(pointls$g, twoD =F)
pointls$sigma <- sqrt(pointls$conds2*lattice2geog)
pointls$Neighborhood <- pointls$twoNem * pointls$conds2 * lattice2geog
#figure out how to break this into different runs
pointls.mcmc <- mcmc(pointls)

#print("calculating statistics")
summ<-summary(pointls.mcmc)
ess<-effectiveSize(pointls.mcmc)
#gelman<-gelman.diag(pointls.mcmc,multivariate=F)
HPD<-HPDinterval(pointls.mcmc)
#create 
sigma_error_fromsigma2 <- pointls.mcmc[which(pointls.mcmc[,6] > HPD[6,1] & pointls.mcmc[,6] < HPD[6,2] ),6]

sigma_from_sigma2 <- 41
```


```{r}

kernelplot_w_sigma2error <- ggplot(data.frame(x=c(0,300)), aes(x)) +
                 map(.x = sample(sigma_error_fromsigma2,1000), .f = function(sigma){
                              stat_function(fun = dexp, args = list(rate = 1/sigma),
                                            colour = "lightblue",
                                            linetype=1,size=0.1,alpha = 0.2) }) +
                stat_function(fun=dexp,args=list(rate = 1/sigma_from_sigma2), linetype=2,
                aes(color="MigraiNe_Sigma"), show.legend = T) +
                ylim(0,0.05) +
                xlab("Alongshore Distance (km)") + ylab("Dispersal probability density") +
                scale_color_manual("Kernel",values = c(MigraiNe_Sigma ="blue"))


```